<a href="https://colab.research.google.com/github/nehalbhagat94/Pytorch_Deep_Learning/blob/main/pytorch_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [ ]:
!pip list

Tensor is a multi dimensional matrix consists of single datatype of elements; similar to numpy arrays and specifically used for deep learning.

In [6]:
np_arr = np.random.rand(3,4)
np_arr, np_arr.dtype

(array([[0.96099981, 0.93280654, 0.06491896, 0.45433637],
        [0.99002706, 0.07577467, 0.99903789, 0.9907845 ],
        [0.90373973, 0.89930656, 0.18530937, 0.98717022]]),
 dtype('float64'))

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d, tensor_2d.dtype, tensor_2d.type(), tensor_2d.size()

(tensor([[ 0.0242,  2.0410,  0.1369, -0.5427],
         [-0.2614,  0.2498,  0.4397,  0.6486],
         [ 0.0752,  2.0662,  0.3317, -0.3080]]),
 torch.float32,
 'torch.FloatTensor',
 torch.Size([3, 4]))

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
np_tensor = torch.tensor(np_arr)
np_tensor, np_tensor.dtype

(tensor([[0.9610, 0.9328, 0.0649, 0.4543],
         [0.9900, 0.0758, 0.9990, 0.9908],
         [0.9037, 0.8993, 0.1853, 0.9872]], dtype=torch.float64),
 torch.float64)

In [12]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_tensor.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_tensor.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_tensor1 = torch.arange(20)
my_tensor1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [19]:
my_tensor1.reshape(5,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [21]:
my_tensor1_reshape = my_tensor1.reshape(5,-1)
my_tensor1[1] = 99
my_tensor1

tensor([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [22]:
my_tensor1_reshape

tensor([[ 0, 99,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [28]:
my_tensor1_reshape[3][1]

tensor(13)

In [29]:
my_tensor[1:6]

tensor([1, 2, 3, 4, 5])

In [31]:
my_tensor1_reshape[2:4,1:3]

tensor([[ 9, 10],
        [13, 14]])

In [35]:
my_tensor1_reshape[-2:,1:3]

tensor([[13, 14],
        [17, 18]])

In [39]:
t = my_tensor1.reshape(10,2)
t

tensor([[ 0, 99],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [99,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

In [40]:
t[:,1]

tensor([99,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
t[:,1:]

tensor([[99],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])

In [44]:
a = torch.tensor([2,3,4,5])
b = torch.tensor([4,7,9,11])
print(a+b)
print(torch.add(a,b))

tensor([ 6, 10, 13, 16])
tensor([ 6, 10, 13, 16])


In [47]:
b-a, torch.sub(b,a)

(tensor([2, 4, 5, 6]), tensor([2, 4, 5, 6]))

In [49]:
a*b, torch.mul(a,b)

(tensor([ 8, 21, 36, 55]), tensor([ 8, 21, 36, 55]))

In [50]:
a/b, torch.div(a,b)

(tensor([0.5000, 0.4286, 0.4444, 0.4545]),
 tensor([0.5000, 0.4286, 0.4444, 0.4545]))

In [51]:
b%a, torch.remainder(b,a)

(tensor([0, 1, 1, 1]), tensor([0, 1, 1, 1]))

In [53]:
a**2, torch.pow(a,2)

(tensor([ 4,  9, 16, 25]), tensor([ 4,  9, 16, 25]))

In [54]:
# a = a+b

a.add_(b)

tensor([ 6, 10, 13, 16])

In [55]:
a   #value reassignment

tensor([ 6, 10, 13, 16])

In [56]:
a.mul_(4)

tensor([24, 40, 52, 64])

In [57]:
a

tensor([24, 40, 52, 64])